name: Train-data
description: Transforms raw data into format needed for YOLO models
inputs:
- {name: Input bucket, type: String, description: 'Data for input 1'}
- {name: Input blob_path, type: String, default: 'training_data.zip', description: 'Number of lines to copy'}
outputs:


metadata:
  annotations:
    author: Mert Kurttutan <kurttutan.mert@gmail.com>
implementation:
  container:
    image: gcr.io/kubeflow-349817/obj-det-kflow199121/try:v4
    command: [
      python3, 
      # Path of the program inside the container
      /opt/workdir/run_training.py,
      --bucket,
      {inputValue: Input bucket},
      --blob-path, 
      {inputPath: Input blob_path},
      --kfp
    ]

    